version: '3.7'

services:
  main_database:
    image: mcr.microsoft.com/mssql/server
    container_name: db_online_store
    user: root
    ports:
      - 1433:1433
    restart: on-failure
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Miguelpombo96!'
    volumes:
      - sqlserver:/var/opt/mssql/data
  app:
    build: .
    container_name: onlinestore
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - main_database
    depends_on:
      - main_database

volumes:
  sqlserver:
    driver: local
